spring:
  application:
    name: fleetman

  datasource:
    url: jdbc:postgresql://localhost:5432/fleetman
    username: admin
    password: password

  jpa:
    hibernate:
      ddl-auto: validate

  mail:
    host: localhost
    port: 1025